### PR TITLE
Ammps integration

### PR DESCRIPTION
**Pull request by nicksawhney**
This pull request adds @mesalas ammps_integration features to the codebase. Important features include:
- Checking for environment variables in the test script and RPC Market code where necessary
- Configurable network parameters for RabbitMQ

A lot of this code was edited in the old hark_portfolio_agents.py file, as this branch was created before the `modules` branch was merged. It is important that these changes be propagated to the correct submodules.

### CODE REVIEW

**Comment by nicksawhney** [comment]
It can be in simulation.py

**Comment by sbenthall** [comment]
Ok, then I need to ask for two things:
 - Fix the merge conflicts (otherwise can't be merged)
 - Remove the duplicate CalibrationSimulation code - either from simulation.py or chum.py

I've started work on refactoring the Simulation code at #82, which interacts with the version of CalibrationSimulation in simulation.py

**Comment by nicksawhney** [comment]
Conflicts resolved and CalibrationSimulation code moved. Should be ready to merge !

**Comment by sbenthall** [comment]
Great. Thank you!

**Pull request merged**
