### PR TITLE
AgentPopulation & AgentPopulationSolution

### PR DESCRIPTION
**Pull request by alanlujan91**

### CODE REVIEW

**Comment by sbenthall** [comment]
Is this ready to merge?

One comment is that if you put this in the sharkfin directory, then it might be easier to write automated tests for this work.

**Comment by alanlujan91** [comment]
@sbenthall I will move it and try to work on tests

**Comment by alanlujan91** [comment]
@sbenthall unsure why tests aren't passing, they pass locally.

**Comment by sbenthall** [comment]
I've reran the tests on GitHub and got failures again.

I've confirmed that they work locally.

However, it looks like the `test_population.py` test is very resource intensive. You can see the spikes in memory and CPU use from two local runs here:

image

I would guess that the memory or compute use is overwhelming what GitHub Actions can support, and that's why it's crashing.
I wonder if it would be possible to scale down the automated test case somehow so that it's less burdensome to compute (but still testing the functionality).

It would also be interesting to know where the performance bottlenecks are.

**Pull request merged**
