### PR TITLE
CRRA is too low, DiscFac too high. 

### PR DESCRIPTION
**Pull request by alanlujan91**
See dashboard.

### CODE REVIEW

**Comment by alanlujan91** [comment]
The issue we saw the other day where Share == 1 always is happening because CRRA = 3 and DiscFac = .99. 

If you move these two parameters around, you can get better non-trivial portfolio shares. For example try CRRA = 10, DiscFac = 0.9, everything else equal. 

This is a well known result of portfolio choice models, they require an unreasonably high CRRA and low DiscFac to get close to matching observed data.

**Comment by sbenthall** [comment]
OK.

What happens when those values are plugged into the Lucas price/dividend ratio formula?
https://github.com/sbenthall/SHARKFin/blob/master/sharkfin/utilities.py#L127-L164

I'm getting an error:
```
>>> ut.price_dividend_ratio_random_walk(0.9, 10, 1.000203, 0.011983, days_per_quarter=90)
subjective_return: 1.0034683918850338
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sb/projects/ufm/SHARKFin/sharkfin/utilities.py", line 162, in price_dividend_ratio_random_walk
    assert subjective_return < 1
AssertionError
```

Recall that the price-dividend ratio is:
image

Imposing the condition:
image

I think what is happening is that when CRRA is increased, the effect of the variance of the dividend shock increases log-quadratically (?) which more than offsets how it dampens the risky asset average return.

image

Does this mean that DiscFac has to be taken down even lower? Can you incorporate this into your dashboard?

**Comment by alanlujan91** [comment]
Correct, this is what I was seeing too with the subjective return > 1.

**Comment by sbenthall** [comment]
tests are now fixed/passing on master, so a new update on this should pass also

**Pull request merged**
