### PR TITLE
Reorganizing the file/directory structure

### PR DESCRIPTION
**Pull request by sbenthall**
Addresses #34

The original file/directory structure of this repository was very messy and ad hoc.

As we professionalize this repository, we should keep a few things in mind:

 - The `sharkfin/` directory will contain the source code of what ultimately will become a Python package published on PyPI
 - Code used for our particular studies has been moved to `simulate/`
 - Code for analyzing the data produced by the simulation has been moved to `analysis/`
 - I've moved the PNL liquidity model code into the `PNL/` directory, to keep that together
 - I've move the script @alanlujan91 developed to test the macroeconomic properties of the model to the `macro/` directory

I believe this is an improvement on the way the code is organized in the repository.

However, in this PR, I have not corrected the paths used in any of the individual files to get things working. It's currently just a demonstration of where things ought to go.

This work can be completed by merging the changes to the paths to this branch `i34`. When completed, this PR can be merged.

### CODE REVIEW

**Comment by nicksawhney** [comment]
I've made the code changes that allow everything to work as intended with the new directory structure. However, it might be a good idea to wait to merge until after the networking code to interact with AMMPS is finalized, since it will be easier to merge that code into the existing codebase than it will to merge into a branch with a different directory structure.

**Comment by sbenthall** [comment]
ok @nicksawhney then why not make a PR for the networking code. We can merge that in, then continue with the refactoring.

**Comment by nicksawhney** [comment]
Sounds good, PR for networking submitted #53

**Comment by sbenthall** [comment]
@nicksawhney I'm still seeing a lot of merge conflicts on this PR.
Can you please resolve them?

**Comment by nicksawhney** [comment]
Conflicts resolved and merged.`simulate/test_simulation.py` works with the new ammps market with the new directory structure.

**Pull request merged**
